accounts:
  root:
    first-name: Lvoxx
    last-name: Aegg Srtist
    email: lvoxxartist@gmail.com
    #! README: Lnmu0AI7Phj1gbO4KMDy
    password: LVOXX@[3pnxLmpqS7JMXFK+WNIxFD7tJjyGMmlMTPBcTkmWg+aUBhS+a3ObDFYmD7kcjFEMlo87DXA6SI9yE+iT8Eqisg==]
    locked: false
    enabled: true
    points: 999999999
    roles: ["ADMIN"]
