spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    #! README: CUyfZRZYJn3Vr0D
    password: LVOXX@[uxUU3zqqAXxzAfhJ5AYLyuATAF7QzobKBKciyUDTn+z/RJQNE8r7UW7abtSMd8tl]
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      platform: h2
