spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: lvoxxartist@gmail.com
    password: <replace yours>
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true