version: '3.5'

services:
  simple-selling-application:
    image: lvoxx/simple-selling-application:1.0.0
    container_name: simple-selling-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    environment:
      LVOXX-SERVER_PRODUCT-DEPLOY: ${PRODUCT-DEPLOY:-false}
      ACCOUNTS_ROOT_EMAIL: ${ROOT_ACCOUNT_EMAIL:-lvoxxartist@gmail.com}
      ACCOUNTS_ROOT_PASSWORD: ${ROOT_ACCOUNT_PASSWORD:-Sup$r3tr@nGP4ssW0r5}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lvoxx-db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_USER:-p0s7GrEs@12*}
    depends_on:
      - postgres