services:
  simple-selling-application:
    image: lvoxx/simple-selling-application:1.0.0
    container_name: simple-selling-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      JAVA_TOOL_OPTIONS: >
        -XX:+UseG1GC
        -Djava.security.egd=file:/dev/./urandom
        -XX:MinRAMPercentage=60.0
        -XX:MaxRAMPercentage=90.0
        -XX:+ExitOnOutOfMemoryError
        -XX:+AlwaysPreTouch
        -XX:+UnlockExperimentalVMOptions
        -XX:+ParallelRefProcEnabled
        -XX:+DisableExplicitGC
        -XX:+PerfDisableSharedMem
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/heapdump
        -Duser.timezone=UTC
        -XX:+UseContainerSupport
        -XX:MaxHeapFreeRatio=30
        -XX:MinHeapFreeRatio=10
        -Xms256m
        -Xmx512m
      JAVA_OPTS: >
        -XX:+UseStringDeduplication
        -XX:+OptimizeStringConcat
        -XX:+UnlockDiagnosticVMOptions
        -XX:+LogCompilation
        -XX:ErrorFile=/logs/hs_err_pid%p.log
        -XX:+CrashOnOutOfMemoryError
        -XX:+AlwaysActAsServerClassMachine
        -Dlog4j2.formatMsgNoLookups=true
      LVOXX-SERVER_PRODUCT-DEPLOY: ${PRODUCT_DEPLOY:-false}
      ACCOUNTS_ROOT_EMAIL: ${ROOT_ACCOUNT_EMAIL}
      ACCOUNTS_ROOT_PASSWORD: ${ROOT_ACCOUNT_PASSWORD:-Sup!r3tr@nGP4ssW0r5}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_PORT: ${MAIL_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_MAIL_PROTOCOL: # stmp
      SPRING_MAIL_PROPERTIES_MAIL_STMP_AUTH: false # true
      SPRING_MAIL_PROPERTIES_MAIL_STMP_AUTH_STARTTLS_ENABLE: false # true
      PAYPAL_CLIENT-ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT-SECRET: ${PAYPAL_CLIENT_SECRET}
      PAYPAL_MODE: ${PAYPAL_MODE}
    networks:
      - lvoxx-networks
    volumes:
      - application-logs:/deploy/simple-selling-application
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  application-logs: