accounts:
  root:
    first-name: Lvoxx
    last-name: Aegg Srtist
    phone: +84-069696969
    email: <change-me>    
    password: <change-me> 
    locked: false
    enabled: true
    points: 999999999
    roles: ["ADMIN"]
