auth-token:
  register-exp-date: 30
  register-exp-date-format: M
  register-revoke-exp-date: 15
  register-revoke-exp-date-format: M

security-path:
  everyone:
    [
      /products,
      /products/**,
      /categories,
      /categories/**,
      /auth,
      /auth/**,
      /media,
      /media/**,
    ]
  user: []
  super-user: []
  admin: [
      /backup,
      /backup/**,
      #! ⇩ ⇩ ⇩ CAUTION: DO NOT public these in production enviroment ⇩ ⇩ ⇩
      
      #! ⇧ ⇧ ⇧ CAUTION: DO NOT public these in production enviroment ⇧ ⇧ ⇧
    ]
  auth-user:
    [/payment, /payment/**, /product-interaction, /product-interaction/**]
  super-user-and-admin: []

client:
  name: simple-selling-application
  roles:
    user: USER
    super-user: SUPER-USER
    admin: ADMIN
