spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <change-me>
    password: <change-me>
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true