spring:
  mail:
    # host: smtp.gmail.com  <- ! CAUTION: Only using this if not passsing env from docker compose
    # port: 587             <- ! CAUTION: Only using this if not passsing env from docker compose
    # username: <change-me> <- ! CAUTION: Only using this if not passsing env from docker compose
    # password: <change-me> <- ! CAUTION: Only using this if not passsing env from docker compose
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true