spring:
  mail:
    host: localhost  
    port: 1025       
    username: ""
    password: "" 
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

mailing:
  register-email:
    subject: Activate Your Account
    path: /activate
    template-url: html/activation.htm