spring:
  mail:
    host: localhost  
    port: 1025       
    username: ""
    password: "" 
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false