media:
  path:
    root: /opt/app/media
    images: /images
    videos: /videos
    compressed: /compressed
    original: /original
  upload-locally: true
  compress:
    image:
      format: jpg
      width: 1920
      height: 1080
      quality: 0.75
    video:
      format: mp4
      resolution: 0.8
      # Audio settings
      audio-channel: 1
      audio-codec: aac
      audio-sample-rate: 44100
      audio-bit-rate: 48000
      # Video settings
      video-codec: libx264
      video-frame-rate: 42
      # Extra configuration
      extra-args-crf: "26"
      extra-args-preset: "faster"
      extra-args-tune: "zerolatency"
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
server:
  compression:
    min-response-size: 2KB
    enabled: true
    mime-types: image/jpeg, image/gif, image/png, video/mp4, video/mpeg, video/mpeg4-generic, application/octet-stream
    ffmpeg: /usr/local/bin/ffmpeg
    ffprobe: /usr/local/bin/ffprobe
