media:
  path:
    root: /opt/app/media
    images: /images
    videos: /videos
    compressed: /compressed
    original: /original
  upload-locally: true
  image-compress:
    format: jpg
    height: 1920
    width: 1080
    quality: 0.8
  video-compress:
    format: mp4
    resolution: 0.75

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
server:
  compression:
    min-response-size: 2KB
    enabled: true
    mime-types: image/jpeg, image/gif, image/png, video/mp4, video/mpeg, video/mpeg4-generic, application/octet-stream
    ffmpeg: /usr/local/bin/ffmpeg
    ffprobe: /usr/local/bin/ffprobe
