lvoxx-server:
  dev-server:
    base-url: http://localhost:9090
    description: Dev BE Server
  prod-server:
    base-url: http://api.lvoxxapplication.com
    description: Product BE Server
  fontend-server:
    base-url:
  contact:
    name: Lvoxx
    email: lvoxxartist@gmail.com
    url: https://github.com/lvoxx
  license:
    name: GNU General Public License
    url: https://www.gnu.org/licenses/gpl-3.0.html
  info:
    title: Simple Selling Application
    version: 1.0.0
    description: This API exposes endpoints to manage users, categories, products and more.
  external-documentation:
    description: Full Documentation
    url: https://github.com/lvoxx/SimpleSellingApplication
  product-deploy: false
  fe-login-url: "{lvoxx-server.fontend-server.base-url/login}"
  payment:
    success-path: "{lvoxx-server.fontend-server.base-url/payment/success}"
    cancel-path: "{lvoxx-server.fontend-server.base-url/payment/cancel?name=%s}"
    error-path: "{lvoxx-server.fontend-server.base-url/payment/error?name=%s}"

fontend-server:
  base: http://localhost:5000
  unknown: "{fontend-server.base}/error?reason=%s"
  login:
    base: "{fontend-server.base}/login"
  active:
    success: "{fontend-server.base}/activate?code=success"
    disabled: "{fontend-server.base}/activate?code=disabled-user"
    expired: "{fontend-server.base}/activate?code=expired"
  payment:
    path: "{fontend-server.base}/payment"
    create: "{fontend-server.payment.path}/create?name=%s"
    success: "{fontend-server.payment.path}/success?name=%s"
    cancel: "{fontend-server.payment.path}/cancel?name=%s"
    error: "{fontend-server.payment.path}/error?name=%s"
# Payment Code:
# 001: Payment Failed
# 002: Product Not Found
# 003: Discount Over Time
