lvoxx-server:
  dev-server:
    base-url: http://localhost:9090
    description: Dev BE Server
  prod-server:
    base-url: http://api.lvoxxapplication.com
    description: Product BE Server
  fontend-server:
    base-url:
  contact:
    name: Lvoxx
    email: lvoxxartist@gmail.com
    url: https://github.com/lvoxx
  license:
    name: GNU General Public License
    url: https://www.gnu.org/licenses/gpl-3.0.html
  info:
    title: Simple Selling Application
    version: 1.0.0
    description: This API exposes endpoints to manage users, categories, products and more.
  external-documentation:
    description: Full Documentation
    url: https://github.com/lvoxx/SimpleSellingApplication
  product-deploy: false
  fe-login-url: "{lvoxx-server.fontend-server.base-url/login}"

fontend-server:
  base: http://localhost:5000
  login:
    base: "{fontend-server.base}/login"
  active:
    success: "{fontend-server.base}/activate?code=success"
    disabled: "{fontend-server.base}/activate?code=disabled-user"
    expired: "{fontend-server.base}/activate?code=expired"
  unknown: "{fontend-server.base}/error?reason=%s"

client:
  name: simple-selling-application
  roles:
    user: USER
    super-user: SUPER-USER
    admin: ADMIN
