lvoxx-server:
  dev-server:
    base-url: http://localhost:9090
    description: Dev BE Server
  prod-server:
    base-url: http://api.lvoxxapplication.com
    description: Product BE Server
  fontend-server:
    base-url: http://localhost:5000
  contact:
    name: Lvoxx
    email: lvoxxartist@gmail.com
    url: https://github.com/lvoxx
  license:
    name: GNU General Public License
    url: https://www.gnu.org/licenses/gpl-3.0.html
  info:
    title: Simple Selling Application
    version: 1.0.0
    description: This API exposes endpoints to manage users, categories, products and more.
  external-documentation:
    description: Full Documentation
    url: https://github.com/lvoxx/SimpleSellingApplication
  product-deploy: false
  payment:
    base-path: /payment
    success-path: /success
    cancel-path: /cancel?rid=%s
    error-path: /error?name=%s

fontend-server:
  base: http://localhost:5000
  error: /error?reason=%s
  login:
    base: /login
  active:
    success: /activate?code=success
    disabled: /activate?code=disabled-user
    expired: /activate?code=expired
  payment:
    base-path: /payment
    create: /create?name=%s
    success: /success?name=%s
    cancel: /cancel?name=%s
    error: /error?name=%s
# Payment Code:
# 001: Payment Failed
# 002: Product Not Found
# 003: Discount Over Time
