apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose.merged.yaml convert --chart --out helm
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: simple-selling-application
  name: simple-selling-application
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: simple-selling-application
