server:
  port: 9090
  servlet:
    context-path: /api

spring:
  application:
    name: simple-selling-application
  config:
    import:
      - config/accounts.yaml
      - config/database.yaml
      - config/email.yaml
      - config/auth.yaml
      - config/server.yaml
      - config/security.yaml
      - config/logging.yaml
      - config/rate-limiter.yaml

---
spring:
  jackson:
    property-naming-strategy: KEBAB_CASE
  messages:
    basename: messages

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /ui-docs
    url: /docs
