server:
  port: 9090
  servlet:
    context-path: /api

spring:
  application:
    name: simple-selling-application
  config:
    import:
      - config/accounts.yml
      - config/database.yml
      - config/email.yml
      - config/auth.yml
      - config/server.yml
      - config/security.yml
      - config/logging.yml
      - config/rate-limiter.yml

---
spring:
  jackson:
    property-naming-strategy: KEBAB_CASE
  messages:
    basename: messages

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /ui-docs
    url: /docs
