INSERT INTO CATEGORY (NAME) VALUES ('Electronics');     --1L
INSERT INTO CATEGORY (NAME) VALUES ('Books');           --2L
INSERT INTO CATEGORY (NAME) VALUES ('Clothing');        --3L
INSERT INTO CATEGORY (NAME) VALUES ('Home Appliances'); --4L
INSERT INTO CATEGORY (NAME) VALUES ('Toys');            --5L
INSERT INTO CATEGORY (NAME) VALUES ('Plant');   --6L