# BASIC - 15 / 2 minutes
# MAX - 1000 / 1 hours
# HEAVY_LOADS - 50 /5 minutes
rate-limiter:
  category:
    find-all: HARD
    id: MAX
    curd: HARD
  product:
    insell-find-all: HEAVY_LOADS
    admin-find-all: SOFT
    insell-id: SOFT
    admin-id: MEDIUM
    manage: MEDIUM
  user:
    find-all: SOFT
    id: SOFT
    manage: MEDIUM

