spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:certs/public-key.pem

rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem

jwt:
  access-token-expiration: 1800000 # 30 minutes
  refresh-token-expiration: 604800000 # 10 days

